# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/tplus-5ef26/api
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: api
  tier: frontend
  type: NodePort
  protocol: TCP
  internalPort: 3000
  externalPort: 8080
  command: ["yarn", "start"]
  
env:
  LOG_LEVEL: "info"
  MONGODB_URI: ""
  DB_NAME: "visioconsult"
  JWT_EXPIRES_IN: "1y"
  JWT_SECRET: "xxxx"  
  CODE_PUSH_ACCESS_KEY: ""
  GATEWAY_AUTH_SECRET: ""

ingress:
  enabled: true
  annotations: 
    # kubernetes.io/ingress.class: "gce"
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: letsencrypt    
  path: /
  hosts:
    - api.visioconsult.app
  tls:
   - secretName: api-visioconsult-app-tls
     hosts:
       - api.visioconsult.app


# Configure a cert-manager Certificate (caution experimental!)
certManager:
  enabled: true
  secretName: api-visioconsult-app-tls
  issuerRef:
    #name: letsencrypt-staging-cluster-issuer
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
  # Note commonName must also be in ingress.hosts
  commonName: api.visioconsult.app

resources: {}
  # limits:
  #   memory: 512Mi
  # requests:
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
