apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: visioconsult-care
spec:
  domains:
  - 'api.visioconsult.care'
  - 'api.beta.visioconsult.care'
  - 'gateway.visioconsult.care'
  - 'mqtt.visioconsult.care'
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: gce
      credentialSecretName: voyager-gce
  storage:
    secret:
      name: cert-visioconsult