apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis
  namespace: infra
spec:
  version: "4.0-v1"
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi