# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mcroth/docker-janus
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: gateway
  tier: frontend
  type: NodePort
  protocol: TCP
  internalPort: 8088
  externalPort: 80

serviceWebsocket:
  name: gateway-websocket
  tier: frontend
  type: NodePort
  protocol: TCP
  internalPort: 8188
  externalPort: 80  
  
env: 
  ENV: production

resources: {}
  # limits:
  #   memory: 512Mi
  # requests:
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
