apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-configmap
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "api.name" . }}    
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote}}
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  MONGODB_URI: {{ .Values.env.MONGODB_URI | quote }}
  FACEBOOK_APP_ID: {{ .Values.env.FACEBOOK_APP_ID | quote }}
  FACEBOOK_APP_SECRET: {{ .Values.env.FACEBOOK_APP_SECRET | quote}}
  SENTRY_DSN: {{ .Values.env.SENTRY_DSN | quote }}
  ONESIGNAL_APP_ID: {{ .Values.env.ONESIGNAL_APP_ID | quote}}
  ONESIGNAL_API_KEY: {{ .Values.env.ONESIGNAL_API_KEY | quote}}
  ONESIGNAL_USER_AUTH_KEY: {{ .Values.env.ONESIGNAL_USER_AUTH_KEY | quote}}
  CLOUDINARY_API_KEY : {{ .Values.env.CLOUDINARY_API_KEY | quote}}
  CLOUDINARY_API_SECRET: {{ .Values.env.CLOUDINARY_API_SECRET | quote}}
  CLOUDINARY_URL: {{ .Values.env.CLOUDINARY_URL | quote}}
  CONSOLE_PWD: {{ .Values.env.CONSOLE_PWD | quote}}
  MJ_APIKEY_PUBLIC: {{ .Values.env.MJ_APIKEY_PUBLIC | quote}}
  MJ_APIKEY_PRIVATE: {{ .Values.env.MJ_APIKEY_PRIVATE | quote}}
  GATEWAY_AUTH_SECRET: {{ .Values.env.GATEWAY_AUTH_SECRET | quote}}
  GOOGLE_CLOUD_BUCKET_NAME: {{ .Values.env.GOOGLE_CLOUD_BUCKET_NAME | quote}}
  GOOGLE_CLOUD_PROJECT_ID: {{ .Values.env.GOOGLE_CLOUD_PROJECT_ID | quote}}