{{ if .Values.image.imagePullSecret }}
{{- $fullName := include "mosquitto.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: private-docker-repo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
{{- if .Values.tls.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-tls-certs
  labels:
    app: {{ template "mosquitto.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  ca.crt: {{ .Values.tls.certificates.ca | b64enc }}
  server.crt: {{ .Values.tls.certificates.cert | b64enc }}
  server.key: {{ .Values.tls.certificates.key | b64enc }}
{{- end }}