apiVersion: v1
kind: Service
metadata:
  name: websocket-{{ template "gateway.fullname" . }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  app.kubernetes.io/name: {{ template "gateway.name" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.serviceWebsocket.externalPort }}
      targetPort: {{ .Values.serviceWebsocket.internalPort }}
      protocol: TCP
      name: {{ .Values.serviceWebsocket.name }}        
  selector:
    app: {{ template "gateway.name" . }}
